### ISSUE TITLE
Accept / Reject Requests

### ISSUE THREAD

**Issue by AngelaLuo49021** [Covaid-co/covaid-mobile#6]
- When a volunteer Rejects a request, it will disappear from the volunteer's home ("cancel this request") also does the same
- When accepted, the request will now show the requester's name instead of "someone needs ur help". 
- When clicking on an accepted request, details like this should be shown: 
- Maybe use the same structure of twitter where if you click on a tweet, it will open up a new page with more details and you swipe left to get back to home.
- Add confirmation!!!
<img width="641" alt="Screen Shot 2020-05-22 at 7 18 35 PM" src="https://user-images.githubusercontent.com/42478474/82717332-14073980-9c61-11ea-8663-f8d3d6b8491b.png"> 
#5 should be completed first before this!!!!!!!!

**Comment by shresta4** [comment]
- [x] Add a confirmation "are you sure you want to accept/reject" 
- [x] Ask for a reason when completing request
- [x] Gray out buttons once someone presses complete or smth so they don't think they can change it again
- [x] Display changes immediately instead of having to refresh
- [x] Bug: Check for page refresh, does information get updated automatically, does it land on pending requests, complete date doesn't show until refresh. The requests themselves seem to be moving tho 
- [x] UI error flatlist
